sudo: false
language: julia
os:
    - osx
    - linux
julia:
    - release
    - nightly
notifications:
    email: false
script:
    - julia -e 'Pkg.clone(pwd()); Pkg.build("FreeType"); Pkg.test("FreeType"; coverage=true)';
    - julia -e 'cd(Pkg.dir("FreeType")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())';
